shopify:
  store_url: https://arcuswear.myshopify.com
  client_id: 7625899de2923f2831fe57d1fafc71b3
  client_secret: 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

google_sheets:
  spreadsheet_id: 1wK6aA1Sny5Ie3Ef8gU8LMgaBMjpNKW7ol1pxVWmGihE
  service_account_path: credentials/service_account.json

profit:
  cost_per_shirt: 12.26
  default_shipping_label_cost: 0.00

sync:
  frequency: daily
  time: "09:00"
